INSERT INTO phone (id, phone_id, make, model, name, available, quantity) VALUES (1, 'samsung-galaxy-s9', "Samsung", "Galaxy S9", "Samsung Galaxy S9", true, 1);
INSERT INTO phone (id, phone_id, make, model, name, available, quantity) VALUES (2, 'samsung-galaxy-s8', "Samsung", "Galaxy S8", "Samsung Galaxy S8", true, 2);
INSERT INTO phone (id, phone_id, make, model, name, available, quantity) VALUES (3, 'samsung-galaxy-s8', "Samsung", "Galaxy S8", "Samsung Galaxy S8", true, 2);
INSERT INTO phone (id, phone_id, make, model, name, available, quantity) VALUES (4, 'motorola-nexus-6', "Motorola", "Nexus 6", "Motorola Nexus 6", true, 1);
INSERT INTO phone (id, phone_id, make, model, name, available, quantity) VALUES (5, 'oneplus-9', "Oneplus", "9", "Oneplus 9", true, 1);
INSERT INTO phone (id, phone_id, make, model, name, available, quantity) VALUES (6, 'apple-iphone-13', "Apple", "iPhone 13", "Apple iPhone 13", true, 1);
INSERT INTO phone (id, phone_id, make, model, name, available, quantity) VALUES (7, 'apple-iphone-12', "Apple", "iPhone 12", "Apple iPhone 12", true, 1);
INSERT INTO phone (id, phone_id, make, model, name, available, quantity) VALUES (8, 'apple-iphone-11', "Apple", "iPhone 11", "Apple iPhone 11", true, 1);
INSERT INTO phone (id, phone_id, make, model, name, available, quantity) VALUES (9, 'apple-iphone-x', "Apple", "iPhone X", "iPhone X", true, 1);
INSERT INTO phone (id, phone_id, make, model, name, available, quantity) VALUES (10, 'nokia-3310', "Nokia", "3310", "Nokia 3310", true, 1);